### ISSUE TITLE
Margin issue on about page

### ISSUE THREAD

**Issue by LoganBradley787** [AtlasAutoware/atlas-autoware#2]
<img width="960" alt="image" src="https://github.com/AtlasAutoware/atlas-autoware/assets/127025561/c88584de-4926-447e-beca-cf19611559d4">

it looks weird

**Comment by eshankiyer** [comment]
![image](https://github.com/AtlasAutoware/atlas-autoware/assets/79593316/99fa941a-1581-4f9a-8aaa-2e732c0735ac)
